module.exports = {
    MMLIFEAPP_BILLBOARD_RANK_TYPE_DISTRICT_WANTED_FOOD: 1,
    MMLIFEAPP_BILLBOARD_RANK_TYPE_FRIEND_WANTED_FOOD: 2,
    MMLIFEAPP_POILIST_ENTRY_TYPE_WANTED_FOOD_CATEGORY_RANKLIST: 3
};